---
- name: "Copy-decrypt Google service account credentials"
  ansible.builtin.copy:
    src: "{{ bkeeper_creds_path }}"
    dest: "/etc/backups-keeper/credentials.json"
    mode: "0660"
    owner: root
    group: root

- name: "Template the configuration file"
  ansible.builtin.template:
    src: "config.yaml.j2"
    dest: "/etc/backups-keeper/config.yaml"
    mode: "0660"
    owner: root
    group: root
