---
- name: "Install | install `backups-keeper`"
  environment:
    PATH: "{{ bkeeper_gopath }}:{{ ansible_env.PATH }}"
  block:
    - name: "Install | check if `backups-keeper` is accessible from PATH"
      changed_when: false
      register: bkeeper_installed_ver
      ansible.builtin.command:
        cmd: backups-keeper --version

    - name: "Install | assert that the requested version is already installed"
      ansible.builtin.assert:
        that: "bkeeper_ver in bkeeper_installed_ver.stdout"
        success_msg: "expected version available ({{ bkeeper_ver }})"
        fail_msg: "expected version: {{ bkeeper_ver }}, actual: {{ bkeeper_installed_ver.stdout }}"

  rescue:
    - name: "Install | clone the private repo"
      ansible.builtin.include_role:
        name: git_clone
      vars:
        git_clone_user: "{{ ansible_user }}"
        git_clone_gh_access_token: "{{ bkeeper_access_token }}"
        git_clone_git_repo: "{{ bkeeper_repo }}"
        git_clone_git_branch: "{{ bkeeper_branch }}"
        git_clone_dest: "{{ bkeeper_branch_clone_dest }}"

    - name: "Install | run 'make clean' preventively"
      notify: "Enable-Restart"
      community.general.make:
        chdir: "{{ bkeeper_branch_clone_dest }}"
        target: "clean"

    - name: "Install | compile and install the downloaded binary"
      notify: "Enable-Restart"
      community.general.make:
        chdir: "{{ bkeeper_branch_clone_dest }}"
        target: "install"

    - name: "Install | run 'make clean' post-installation"
      notify: "Enable-Restart"
      community.general.make:
        chdir: "{{ bkeeper_branch_clone_dest }}"
        target: "clean"

    - name: "Install | deploy systemd unit files"
      notify: "Enable-Restart"
      community.general.make:
        chdir: "{{ bkeeper_branch_clone_dest }}"
        target: "service"


- name: "Install | configure the invocation interval in the deployed timer"
  notify: "Enable-Restart"
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/backups-keeper.timer
    regexp: "^OnCalendar"
    line: "OnCalendar={{ bkeeper_timer_oncalendar }}"
    owner: root
    group: root
    mode: '0644'
