---
- name: "Install | check if `backups-keeper` is accessible from $PATH"
  block:
    - name: "Install | check if `backups-keeper` is accessible from $PATH"
      changed_when: false
      register: bkeeper_installed_ver
      ansible.builtin.command:
        cmd: backups-keeper --version

    - name: "Install | assert that the requested version is already installed"
      ansible.builtin.assert:
        that: "bkeeper_ver in bkeeper_installed_ver.stdout"

  rescue:
    - name: "Install | run 'make clean' preventively"
      notify: "enable-run"
      community.general.system.make:
        chdir: "{{ bkeeper_branch_clone_dest }}"
        target: "clean"

    - name: "Install | compile and install the downloaded binary"
      notify: "enable-run"
      community.general.system.make:
        chdir: "{{ bkeeper_branch_clone_dest }}"
        target: "install"

    - name: "Install | run 'make clean' post-installation"
      notify: "enable-run"
      community.general.system.make:
        chdir: "{{ bkeeper_branch_clone_dest }}"
        target: "clean"

    - name: "Install | deploy systemd unit files"
      notify: "enable-run"
      community.general.system.make:
        chdir: "{{ bkeeper_branch_clone_dest }}"
        target: "service"

    - name: "Install | configure the invocation interval in the deployed timer"
      notify: "enable-run"
      ansible.builtin.lineinfile:
        path: /etc/backups-keeper/backups-keeper.timer
        regexp: "^OnCalendar"
        line: "OnCalendar={{ bkeeper_timer_oncalendar }}"
        owner: root
        group: root
        mode: '0644'
