---
- name: "Install | install `backups-keeper`"
  block:
    - name: "Install | check if `backups-keeper` is accessible from PATH"
      changed_when: false
      register: bkeeper_installed_ver
      ansible.builtin.command:
        cmd: backups-keeper --version

    - name: "Install | assert that the requested version is already installed"
      ansible.builtin.assert:
        that: "bkeeper_ver in bkeeper_installed_ver.stdout"
        success_msg: "expected version available ({{ bkeeper_ver }})"
        fail_msg: "expected version: {{ bkeeper_ver }}, actual: {{ bkeeper_installed_ver.stdout }}"

  rescue:
    - name: "Install | create a temporary directory"
      register: tmpdir
      ansible.builtin.tempfile:
        state: directory
        suffix: backups-keeper

    - name: "Install | fetch binary release"
      ansible.builtin.uri:
        # method: "POST"
        url: "{{ gh_asset_url }}"
        headers:
          accept: "application/octet-stream"
          Content-Disposition: "attachment"
        follow_redirects: safe
        dest: "{{ tmpdir.path }}/{{ tarball_name }}"

    - name: "Install | unpack the release tarball"
      ansible.builtin.unarchive:
        src: "{{ tmpdir.path }}/{{ tarball_name }}"
        dest: "{{ tmpdir.path }}"

    - name: "Install | deploy distribution files"
      notify: "Enable-Restart"
      loop:
        - {name: "backups-keeper", mode: "0770", dest: "/usr/bin/backups-keeper"}
        - {name: "backups-keeper.service", mode: "0660", dest: "/etc/systemd/system/backups-keeper.service" }
        - {name: "backups-keeper.timer", mode: "0660", dest: "/etc/systemd/system/backups-keeper.timer" }
      ansible.builtin.copy:
        remote_src: true
        src: "{{ tmpdir.path }}/{{ item.name }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"

    - name: "Install | clean up the temporary directory"
      when: tmpdir.path is defined
      ansible.builtin.file:
        path: "{{ tmpdir.path }}"
        state: absent

    # - name: "Install | deploy systemd unit files"
    #   notify: "Enable-Restart"
    #   community.general.make:
    #     chdir: "{{ bkeeper_branch_clone_dest }}"
    #     target: "service"
